org: dylancabezas
service: api-web-scraping

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::496585850746:role/LabRole

functions:
  scrape_table:
    handler: SCRAPING_TABLE.lambda_handler
    package:
      include:
        - SCRAPING_TABLE.py
    events:
      - http:
          path: /scrape/table
          method: get
          cors: true

resources:
  Resources:
    TablaWebScrapping:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TablaWebScrapping
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
